name: google_mlkit_commons
description: A Flutter plugin to use Google's ML Kit Text Recognition API for iOS and Android.
version: 0.2.0
homepage: https://github.com/bharat-biradar/Google-Ml-Kit-plugin

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.google_mlkit_commons
        pluginClass: GoogleMlKitCommonsPlugin
      ios:
        pluginClass: GoogleMlKitCommonsPlugin
